development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
  fee_percentage: <%= ENV["FEE_PERCENTAGE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
  fee_percentage: <%= ENV["FEE_PERCENTAGE"] %>
